version: "3"

services:
  app:
    depends_on:
      - "redis"
    build:
      context: ./shorten-app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./shorten-app:/app"
    env_file:
      - "./shorten-app/env/redis.env"
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    container_name: shorten-app
  
  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - "redis-data:/data"
    container_name: redis
  
volumes:
  redis-data: {}